# Generated by Django 2.2.5 on 2019-09-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=250)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app16.News')),
            ],
        ),
    ]
