# Generated by Django 3.0.3 on 2020-02-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('full_name', models.CharField(max_length=50)),
                ('contact_address', models.CharField(max_length=50)),
            ],
        ),
    ]
